name: blog_app
description: Blog App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  auto_route: ^6.0.5
  dio: ^5.1.1
  flutter:
    sdk: flutter
  flutter_form_builder: ^7.8.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.4
  flutter_widget_from_html: ^0.10.0
  form_builder_validators: ^8.5.0
  google_language_fonts: ^2.0.0
  hive_flutter: ^1.1.0
  hydrated_state_notifier: ^1.0.0
  hydrated_state_notifier_hive: ^1.0.0
  intl: ^0.17.0
  lottie: ^2.3.2
  openapi:
    path: api
  path_provider: ^2.0.14
  platform_info: ^3.2.0
  talker: ^2.4.0
  talker_dio_logger: ^1.2.2
  velocity_x: ^3.6.0

dev_dependencies:
  auto_route_generator: ^6.0.3
  build_runner: ^2.3.3
  custom_lint: ^0.3.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  riverpod_lint: ^1.3.0
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/animation/
