name: blog_app
description: Blog App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_route: ^7.1.0
  dio: ^5.1.2
  flex_color_scheme: ^7.0.5
  flutter:
    sdk: flutter
  flutter_form_builder: ^8.0.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  flutter_widget_from_html: ^0.10.0
  form_builder_validators: ^8.6.1
  google_language_fonts:
    git:
      url: https://github.com/Shreemanarjun/google-language-fonts-flutter
      ref: v3.0.0
  hive_flutter: ^1.1.0
  hydrated_state_notifier: ^1.0.0
  hydrated_state_notifier_hive: ^1.0.0
  intl: ^0.17.0
  lottie: ^2.3.2
  openapi:
    path: api
  path_provider: ^2.0.15
  platform_info: ^3.2.0
  talker: ^2.4.1
  talker_dio_logger: ^1.2.2
  velocity_x:
    git:
      url: https://github.com/Shreemanarjun/VelocityX.git
      ref: v4.0-release # branch name

dependency_overrides:
  intl: '0.18.1'

dev_dependencies:
  auto_route_generator: ^7.0.0
  build_runner: ^2.4.2
  custom_lint: ^0.3.4
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  riverpod_lint: ^1.3.1
  riverpod_test: ^0.1.3
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/animation/
